### ISSUE TITLE
Clone size 

### ISSUE THREAD

**Issue by sulthonuladib** [iamcodernitesh/i3wm-ez#2]
![Screenshot from 2022-02-23 00-50-53](https://user-images.githubusercontent.com/57745493/155190279-b2883300-8335-454e-8ec5-f41689a9d726.png)

why my clone size more than 250 MB from this repos ????

**Comment by iamcodernitesh** [comment]
lol. It's the wallpapers

**Comment by iamdevnitesh** [comment]
It's the wallpaper size in .git/objects/pack . Let me just clear it. Thanks for notifying it.

**Comment by iamdevnitesh** [comment]
Issue solved.

**Comment by sulthonuladib** [comment]
there's nothing, look again at your repo
