### ISSUE TITLE
Reference to non-existant wallpaper

### ISSUE THREAD

**Issue by beingforthebenefit** [iamcodernitesh/i3wm-ez#5]
There is a [line](https://github.com/iamdevnitesh/i3wm-ez/blob/1abcba2eea428e3ff4c2bd4ed61ab1f7613b4a3c/popOS.sh#L56) in `popOS.sh` referencing a non-existent `Wallpapers/landscape1.jpg` which results in an error.

**Comment by iamdevnitesh** [comment]
@beingforthebenefit Solved the issue. Added Wallpapers folder in the repository.
